shawnrivers/nogilib

src/client/components/templates/Page/components/NavigationBar/index.tsx, src/client/components/templates/Page/components/Sidebar/index.tsx, src/client/components/templates/Page/index.tsx
Skip Keyboard `Tab` focus for invisible component
=> Fix Keyboard Tab Focus

src/client/components/atoms/Hashtag/index.tsx, src/client/components/molecules/cards/ArtworkCard/index.tsx, src/client/components/molecules/cards/HorizontalCard/index.tsx, src/client/components/molecules/cards/MemberCard/index.tsx, src/client/components/templates/Page/components/Header/index.tsx, src/client/features/Album/template.tsx, src/client/features/Discography/template.tsx, src/client/features/Member/template.tsx, src/client/features/Members/template.tsx, src/client/features/Search/components/SearchResultCategory/index.tsx, src/client/features/Search/template.tsx, src/client/features/Song/template.tsx, src/client/hooks/useIntl.ts, src/client/i18n/translations.ts, src/data/members.json, src/pages/404.tsx, src/pages/search.tsx, src/server/actors/Members/raw/editor/secondGen.ts
- Add `lang` attributes
- Add Terada Ranze's Instagram account
=> Imporve i18n

src/data/members.json, src/server/actors/Members/raw/editor/firstGen.ts
- Added Higuchi Hina Instagram account
=> Add Higuchi Instagram account

src/client/features/Member/template.tsx
- Fixed member page `<ol>` list counting
=> Fix list counting

.github/pull_request_template.md, .github/release-drafter.yml, .github/workflows/draft.yml
- Added release draft for better release docs
- Simplified PR tempalte
=> Add GitHub release draft

.github/release-drafter.yml
- Added name and tag template for release draft
=> Add name and tag template for release draft

.github/release-drafter.yml
- Modify release draft template
=> Modify release draft template

package-lock.json, package.json, src/client/features/Song/template.tsx
=> Remove unused dependencies

src/data/discography.json, src/data/members.json, src/data/songs.json, src/server/actors/Discography/raw/editor/singles/26.ts, src/server/actors/Members/raw/editor/secondGen.ts, src/server/actors/Songs/constants/songTitle.ts, src/server/actors/Songs/raw/editor/singles/26.ts
- Add Sasaki Kotoko profile site link
- Add Hori Miona graduation soso songs 冷たい水の中
- Add 僕は僕を好きになる lyrics
=> Add Hori Miona graduation solo and Sasaki Kotoko profile site link

src/data/members.json, src/server/actors/Members/raw/editor/thirdGen.ts
=> Add Yoda Yuki Instagram

src/data/members.json, src/server/actors/Members/raw/editor/firstGen.ts
- Remove Maiyan and Kana blog links
=> Remove Maiyan and Kana blog links

.github/release-drafter.yml
- Add release version resolving
=> Add release version resolving

src/client/features/Member/container.tsx, src/pages/discography.tsx, src/pages/members.tsx, src/server/actors/Members/converters.ts, src/server/actors/Members/raw/creator.ts, src/server/actors/Songs/converters.ts, src/utils/arrays.ts, src/utils/sorting.ts
- Sort members by name
- Refactor sorting utils
=> Sort members by name

src/client/components/templates/Page/index.tsx, src/client/i18n/translations.ts, src/client/styles/tokens/elevation.ts
- Add skip to content link for better keyboard navigation experience
=> Add skip to content link

src/client/components/templates/Page/index.tsx
- Fix skip link transition styles
=> Fix skip link styles

gatsby-config.js, package.json, src/client/features/Album/template.tsx, src/client/features/Discography/template.tsx, src/client/features/Member/template.tsx, src/client/features/Members/template.tsx, src/client/features/Search/template.tsx, src/client/features/Song/template.tsx, src/client/hooks/useSiteMetadata.ts, src/client/i18n/translations.ts, src/client/layouts/Helmet.tsx, src/client/layouts/PageHelmet.tsx, src/utils/strings.ts
- add page title to every page
- add site metadata in Gatsby config
- change GraphQL playground IDE
=> Add page title to every page

README.md, gatsby-config.js
- Fix site URL to `nogilib.com`
=> Fix site URL

src/client/components/atoms/BaseLink/index.tsx, src/client/components/molecules/links/TextLink/index.tsx
=> Fix tabs styles

README.md
- Add copyrights section in README for warning the use of this project
=> Add copyrights warning

src/data/members.json, src/server/actors/Members/raw/editor/fourthGen.ts
- Add new 4th gen member personal blogs
=> Add new 4th gen member personal blogs

src/client/hooks/useLocalStorageForContext.ts
=> Fix default language

src/data/member.json, src/server/actors/Members/raw/editor/firstGen.ts
=> Add Nishino Twitter account

src/data/member.json, src/server/actors/Members/raw/editor/thirdGen.ts
- Add Umezawa Instagram account
=> Add Umezawa Instagram account

package.json
- Auto-generate data on commit (only for raw data)
=> Auto-generate data on commit

src/client/components/molecules/TextSwitchLinkGroup/index.tsx, src/client/components/molecules/cards/ArtworkCard/index.tsx, src/client/components/molecules/cards/HorizontalCard/index.tsx, src/client/components/molecules/cards/MemberCard/index.tsx, src/client/components/templates/Page/components/Header/index.tsx, src/client/components/templates/Page/components/NavigationBar/index.tsx, src/client/components/templates/Page/components/Sidebar/index.tsx, src/client/i18n/translations.ts, src/pages/index.tsx
- Fix ARIA labels
- Fix ARIA properties
- Fix semantics
=> Improve screen reader annoucements

src/data/member.json, src/data/song.json, src/server/actors/Members/raw/editor/firstGen.ts, src/server/actors/Songs/raw/editor/singles/26.ts
- Add 26th single creators
- Add Matsui Rena YouTube channel
=> Update 26th single data

src/client/components/atoms/images/GatsbyImage/index.tsx, src/client/components/atoms/images/GirdImage/index.tsx, src/client/components/molecules/cards/ArtworkCard/index.tsx, src/pages/index.tsx
- Fix Gatsby image border-radius for Safari
=> Fix Gatsby image border-radius for Safari

.circleci/config.yml
=> ci: remove build step from CI for better CI speed

src/client/components/layout/Page/components/NavigationBar/index.tsx
- Set `NEXT_LOCALE` to preserve language setting
=> Preserve lang settings

src/data/member.json, src/server/actors/Members/raw/editor/firstGen.ts
- Fix Nanase photo book title typo
Big Thanks to [@husigiyt](https://twitter.com/husigiyt/status/1363304049890631680) for pointing out this issue!
=> Fix Nanase photo book title

src/client/components/layout/PageContent.tsx, src/client/components/molecules/cards/ArtworkCard/index.tsx, src/client/i18n/hooks/useIntl.ts, src/client/i18n/translations.ts, src/client/utils/url.ts, src/pages/discography/[id].tsx, src/pages/discography/index.tsx, src/pages/search.tsx, src/pages/songs/[id].tsx
- Add a "digital" filter on the discography page
- Fix album type translation
- Remove numbering for digital albums
=> Add a "digital" filter on the discography page

src/client/store/search/context.tsx, src/client/store/search/hook/useSearchQuery.ts, src/client/store/search/reducer.ts, src/pages/_app.tsx, src/pages/search.tsx
- Move search query and results to a new Context
- Preserve the search query and results after navigating to another page
=> Preserve search query

src/pages/members/[name].tsx
- Remove the position counter component on the member page
=> Remove position counter

src/client/components/pages/member/PositionBadge/index.tsx, src/client/i18n/translations.ts, src/pages/members/[name].tsx
Member page
- Hide unnecessary position badges
- Modify divider color
=> Hide unnecessary position badges

.github/workflows/check.yml
=> Add GitHub Actions for CI

.github/auto-merge.yml, .github/workflows/auto-create-dependabot-branch.yml, .github/workflows/auto-merge.yml
- Auto merge minor and patch dependencies update
- Auto create `update-dependencies` branch after it's been deleted
=> Refine Dependabot workflow

src/data/member.json, src/server/actors/Members/raw/editor/secondGen.ts
- Add Watanabe Miria's Instagram
=> Add Watanabe Miria's Instagram

src/data/member.json, src/server/actors/Members/raw/editor/thirdGen.ts
=> Add Sato Kaede's Instagram

src/data/member.json, src/data/members.json, src/server/actors/Members/raw/editor/secondGen.ts
=> Add Hori graduation

src/data/member.json, src/server/actors/Members/raw/editor/secondGen.ts
=> Add Hori official site

src/data/member.json, src/server/actors/Members/raw/editor/secondGen.ts
=> Fix Hori Instagram

src/data/album.json, src/data/discography.json, src/data/member.json, src/data/search.json, src/data/song.json, src/server/actors/Discography/constants/cdTitle.ts, src/server/actors/Discography/raw/editor/singles/27.ts, src/server/actors/Discography/raw/editor/singles/index.ts, src/server/actors/Songs/constants/songTitle.ts, src/server/actors/Songs/raw/editor/singles/27.ts, src/server/actors/Songs/raw/editor/singles/index.ts
=> Add 27th single formation

src/data/member.json, src/server/actors/Members/raw/editor/firstGen.ts
=> Add Maya Instagram

src/data/member.json, src/server/actors/Members/raw/editor/secondGen.ts
=> Add Hinako Instagram

src/data/album.json, src/data/discography.json, src/data/search.json, src/data/song.json, src/server/actors/Discography/constants/cdTitle.ts, src/server/actors/Discography/raw/editor/singles/27.ts, src/server/actors/Songs/constants/songTitle.ts, src/server/actors/Songs/raw/editor/singles/27.ts
=> Update 27th single title

.eslintrc.js, package-lock.json, package.json, src/client/libs/axe/index.ts, src/pages/_app.tsx, src/utils/env.ts
- Logging a11y warning in development using `@axe-core/react`
- Make ESLint a11y plugin rules stricter
=> Automate a11y testing

src/data/member.json, src/server/actors/Members/raw/editor/secondGen.ts
- Add Yonetoku Instagram and Twitter
=> Add Yonetoku social media

src/client/components/layout/PageHelmet.tsx
=> Fix favicon

src/data/member.json, src/server/actors/Members/raw/editor/firstGen.ts
=> Add Marika Twitter

src/data/member.json, src/server/actors/Members/raw/editor/firstGen.ts
=> Add Nojo Twitter

.eslintrc.js, src/client/components/layout/PageHelmet.tsx
- Support Safari 15 theme color
=> Adapt Safari 15 Theme color

src/client/components/atoms/BaseButton/index.tsx, src/client/components/atoms/Card/index.tsx, src/client/components/atoms/Surface/index.tsx, src/client/components/atoms/image/AspectRatioImage/index.tsx, src/client/components/atoms/image/Image/PolyfilledLazyImage/Component.tsx, src/client/components/atoms/image/Image/index.tsx, src/client/components/layout/Page/index.tsx, src/client/components/molecules/links/TextLink/index.tsx, src/client/store/emotion/provider.tsx, src/pages/index.tsx, src/pages/search.tsx
- Add image background color as loading placeholder
- Use hover styles as focus styles
- Prevent disabled link from receiving focus
=> Refine styles

src/data/member.json, src/server/actors/Members/raw/editor/secondGen.ts
=> Add Miona TikTok

src/data/member.json, src/server/actors/Members/raw/editor/firstGen.ts
- Add Kawamura Mahiro's official website
=> Add Rotty official site

src/data/member.json, src/server/actors/Members/raw/editor/firstGen.ts
=> Add Asuka's Instagram

src/data/album.json, src/data/discography.json, src/data/member.json, src/data/search.json, src/data/song.json, src/server/actors/Discography/constants/cdTitle.ts, src/server/actors/Discography/raw/editor/singles/28.ts, src/server/actors/Discography/raw/editor/singles/index.ts, src/server/actors/Songs/constants/songTitle.ts, src/server/actors/Songs/raw/editor/singles/28.ts, src/server/actors/Songs/raw/editor/singles/index.ts
=> 28th single formation

src/data/member.json, src/server/actors/Members/raw/editor/thirdGen.ts
- Add Mukai Hazuki's Instagram
=> Add Hazuki Instagram

src/data/member.json, src/server/actors/Members/raw/editor/firstGen.ts
- Add Matsumura Sayuri's Twitter
- Remove Matsumura Sayuri's blog and 755
=> Update Sayuringo websites

src/data/member.json, src/data/members.json, src/server/actors/Members/raw/editor/secondGen.ts
- Add Ito Junna and Watanabe Miria's graduation
=> Add Junna and Miria graduation

src/data/member.json, src/data/members.json, src/server/actors/Members/raw/editor/thirdGen.ts
- Update Ozono Momoko graduation
=> Update Momoko graduation

src/data/member.json, src/server/actors/Members/raw/editor/thirdGen.ts
- Add Yoshida Ayano Christie Instagram
=> Add Christie Instagram

src/data/song.json, src/server/actors/Songs/raw/editor/singles/28.ts
- Update the formation of _マシンガンレイン_
- Add more creators information
=> Add more 28th single info

src/data/album.json, src/data/search.json, src/data/song.json, src/server/actors/Songs/raw/editor/singles/28.ts
- Add more 28th single creators
=> Add more 28th single creators

.storybook/preview.js
=> Fix Storybook

src/data/member.json, src/server/actors/Members/raw/editor/thirdGen.ts
=> Add Reno Instagram

src/client/i18n/translations.ts, src/data/album.json, src/data/search.json, src/data/song.json, src/server/actors/Discography/raw/editor/albums/best.ts, src/server/actors/Songs/constants/songTitle.ts, src/server/actors/Songs/raw/editor/albums/best.ts, src/server/actors/Songs/raw/editor/albums/index.ts
- Add 「最後のTight Hug」
- Add more translation
=> Add more best album info

src/client/components/layout/PageContent.tsx, src/client/i18n/hooks/useIntl.ts, src/pages/discography/[id].tsx, src/pages/members/[name].tsx, src/pages/songs/[id].tsx
- Remove the back button
- Add sub-title on the song page
- Prevent scroll position restoration
=> Remove the back button

.github/dependabot.yml
- Specify dependabot PR labels
=> Specify dependabot PR labels

src/data/member.json, src/server/actors/Members/raw/editor/thirdGen.ts
- Add Sakaguchi Tamami's Instagram
=> Add Tamami Instagram

src/data/song.json, src/server/actors/Songs/raw/editor/albums/best.ts
=> Add「最後のTight Hug」formation

.github/workflows/draft.yml, package.json, scripts/package.json, scripts/src/update-data/release.sh, scripts/src/update-data/start.sh
- Make `main` the default branch and remove the `dev` branch
=> Default main branch

src/data/song.json, src/server/actors/Songs/models.ts, src/server/actors/Songs/raw/creator.ts, src/server/actors/Songs/raw/editor/albums/best.ts, src/server/pages/song.ts
- Fix profile images for ゆっくりと咲く花
=> Fix profile images for ゆっくりと咲く花

src/data/member.json, src/data/members.json, src/server/actors/Members/raw/editor/firstGen.ts
- Add Takayama Kazumi's graduation
=> Add Kazumin graduation

src/data/member.json, src/server/actors/Members/raw/editor/firstGen.ts
- Update Ikuta Erika's photo book title
=> Update Ikuchan photo book title

src/data/member.json, src/server/actors/Members/raw/editor/firstGen.ts
=> Add Reika Twitter

src/data/member.json, src/data/members.json, src/server/actors/Members/raw/editor/secondGen.ts
- Update Terada Ranze's graduation
=> Update Ranze graduation

src/data/member.json, src/server/actors/Members/raw/editor/secondGen.ts
=> Add Junna's Twitter

src/db/result/member.json, src/db/result/members.json, src/db/src/actors/Members/raw/editor/firstGen.ts
- Update Ikuta Erika's graduation
=> Update Ikuchan's graduation

src/db/result/member.json, src/db/src/actors/Members/raw/editor/firstGen.ts
- Add Ikuta Erika's Twitter account
=> Add Ikuchan Twitter

src/db/result/member.json, src/db/src/actors/Members/raw/editor/thirdGen.ts
- Add Ozono Momoko's YouTube channel
=> Add Momoko YouTube

src/db/result/member.json, src/db/result/members.json, src/db/src/actors/Members/raw/editor/secondGen.ts
- Add Shinuchi Mai's graduation
=> Add Maichun graduation

src/db/result/member.json, src/db/result/members.json, src/db/src/actors/Members/raw/editor/firstGen.ts
- Update Hoshino Minami's graduation
=> Update Minami graduation

src/db/result/member.json, src/db/src/actors/Members/raw/editor/firstGen.ts, src/db/src/actors/Members/raw/editor/fourthGen.ts, src/db/src/actors/Members/raw/editor/secondGen.ts, src/db/src/actors/Members/raw/editor/thirdGen.ts
- Fix member profile and blog URLs
=> Fix member profile and blog URLs

src/db/result/album.json, src/db/result/discography.json, src/db/result/member.json, src/db/result/search.json, src/db/result/song.json, src/db/src/actors/Discography/constants/cdTitle.ts, src/db/src/actors/Discography/raw/editor/singles/29.ts, src/db/src/actors/Discography/raw/editor/singles/index.ts, src/db/src/actors/Songs/raw/editor/singles/29.ts, src/db/src/actors/Songs/raw/editor/singles/index.ts
- Add 29th single
- Add 29th single formation without the center
- The center will be added as soon as the announcement is made
=> Add 29th single formation (without the center)

src/db/result/member.json, src/db/src/actors/Members/raw/editor/secondGen.ts
- Add Suzuki Ayane's Instagram account
=> Add Ayane Instagram

next.config.js, package-lock.json, package.json
- Replace React with Preact to improve performance
=> Replace React with Preact

src/db/result/song.json, src/db/src/actors/Songs/raw/editor/singles/29.ts
- Update 29th single songs info
=> Update 29th single songs info

src/db/result/song.json, src/db/src/actors/Songs/raw/editor/singles/29.ts
- Add 29th single song creators
- Add 29th single under center
=> Update 29th single data

src/client/components/layout/PageHelmet.tsx, src/client/components/molecules/cards/MemberCard/index.tsx
- Update status bar color based on the theme
=> Fix status bar color

src/pages/search.tsx
- Fix search clear button alignment
=> Fix search clear button alignment

src/db/result/song.json, src/db/src/actors/Songs/raw/editor/singles/29.ts
- Add 29th single MV directors
=> Add 29th single MV directors

src/db/result/member.json, src/db/src/actors/Members/raw/editor/firstGen.ts
- Add Takayama Kazumi' staff Twitter
=> Add Kazumin Twitter

src/db/result/member.json, src/db/src/actors/Members/raw/editor/fifthGen.ts
=> Add 5th member blog

src/db/result/member.json, src/db/result/members.json, src/db/src/actors/Members/raw/editor/secondGen.ts
- Add Kitano Hinako's graduation
=> Add Hinako graduation

src/client/i18n/translations.ts, src/db/result/member.json, src/db/src/actors/Members/raw/editor/fifthGen.ts
- Add  5th gen member's glow stick colors
- Update translations
=> Add 5th gen member glow stick colors

src/client/components/layout/Page/components/SettingsMenu/index.tsx
- Specify `lang` in the settings menu for language radio buttons
=> Fix HTML lang

src/db/result/member.json, src/db/src/actors/Members/raw/editor/firstGen.ts
- Update Nojo Ami's photo book title
=> Update Nojo's photo book title

src/db/result/member.json, src/db/src/actors/Members/raw/editor/secondGen.ts
- Add Hori Miona's Twitter account
=> Add Hori Twitter account

src/client/components/atoms/Hashtag/index.tsx, src/client/components/atoms/Typography/index.tsx, src/client/components/layout/Page/components/SettingsMenu/index.tsx, src/client/components/layout/Page/components/TopNavigationBar/index.tsx, src/client/components/layout/Page/index.tsx, src/client/components/layout/PageContent.tsx, src/client/components/molecules/TextDivider/index.tsx, src/client/components/molecules/TextSwitchLinkGroup/index.tsx, src/client/components/molecules/cards/ArtworkCard/index.tsx, src/client/components/molecules/cards/HorizontalCard/index.tsx, src/client/components/molecules/cards/MemberCard/index.tsx, src/client/components/molecules/links/TextLink/index.tsx, src/client/components/molecules/typography/SectionSubtitle.tsx, src/client/components/molecules/typography/info/InfoItemLabel.tsx, src/client/components/molecules/typography/info/InfoItemValue.tsx, src/client/components/pages/member/GlowStickBadge/index.tsx, src/client/components/pages/member/PositionBadge/index.tsx, src/client/components/pages/member/PositionCounter/index.tsx, src/client/components/pages/search/SearchResultCategory/index.tsx, src/client/store/emotion/provider.tsx, src/pages/index.tsx, src/pages/members/[name].tsx, src/pages/search.tsx, src/pages/songs/[id].tsx
=> Improve semantics

src/db/result/member.json, src/db/src/actors/Members/raw/editor/secondGen.ts
- Remove Hori Miona's Twitter account
=> Remove Miona's Twitter

src/db/result/album.json, src/db/result/discography.json, src/db/result/member.json, src/db/result/members.json, src/db/result/search.json, src/db/result/song.json, src/db/src/actors/Discography/raw/editor/singles/30.ts, src/db/src/actors/Discography/raw/editor/singles/index.ts, src/db/src/actors/Members/raw/editor/secondGen.ts, src/db/src/actors/Songs/raw/editor/singles/30.ts, src/db/src/actors/Songs/raw/editor/singles/index.ts
- Add 30th single formation
- Add Yamazaki Rena's graduation
=> Add 30th single formation

src/db/result/album.json, src/db/result/discography.json, src/db/result/member.json, src/db/result/search.json, src/db/result/song.json, src/db/src/actors/Discography/constants/cdTitle.ts, src/db/src/actors/Discography/raw/editor/singles/30.ts, src/db/src/actors/Members/raw/editor/secondGen.ts, src/db/src/actors/Songs/constants/songTitle.ts, src/db/src/actors/Songs/raw/editor/singles/30.ts
- Update 30th single title
- Add Yamazaki Rena's Twitter
=> Update 30th single title

src/db/result/member.json, src/db/src/actors/Members/raw/editor/secondGen.ts
- Remove Hori Miona's Twitter account
=> Remove Miona Twitter

src/db/result/member.json, src/db/result/song.json, src/db/src/actors/Members/raw/editor/fourthGen.ts, src/db/src/actors/Songs/raw/editor/singles/30.ts
- Update 30th single songs data
- Add Yakubo Mio's Instagram
=> Update 30th single data

src/db/result/member.json, src/db/src/actors/Members/raw/editor/secondGen.ts
=> Add Kitano Twitter

src/db/result/member.json, src/db/src/actors/Members/raw/editor/firstGen.ts, src/db/src/actors/Members/raw/editor/thirdGen.ts
- Add Nakamoto Himeka's Instagram
- Add Ito Riria's Instagram
=> Add Himetan and Riria Instagram

src/utils/sorting.ts
- Fix 5th gen group sort in members page
=> Sort 5th gen correctly

src/db/result/member.json, src/db/src/actors/Members/raw/editor/secondGen.ts
- Add Kitano Hinako YouTube and official website
- Remove Kitano Hinako old websites
=> Update Kiichan data

src/client/store/emotion/provider.tsx
- Add `color-scheme` to adapt OS UI to the color scheme
=> Add `color-scheme` to adapt OS UI to the color scheme

src/db/result/member.json, src/db/src/actors/Members/raw/editor/fourthGen.ts
- Add Kanagawa Saya's Instagram account
=> Add yanchan Instagram

src/db/result/album.json, src/db/result/discography.json, src/db/result/member.json, src/db/result/members.json, src/db/result/search.json, src/db/result/song.json, src/db/src/actors/Discography/constants/cdTitle.ts, src/db/src/actors/Discography/raw/editor/singles/31.ts, src/db/src/actors/Discography/raw/editor/singles/index.ts, src/db/src/actors/Members/raw/editor/firstGen.ts, src/db/src/actors/Songs/constants/songTitle.ts, src/db/src/actors/Songs/raw/editor/singles/31.ts, src/db/src/actors/Songs/raw/editor/singles/index.ts
- Add Higuchi Hina graduation
- Add 31st single info
=> Add Hinachima Graduation and 31st Single

src/db/result/member.json, src/db/result/song.json, src/db/src/actors/Discography/raw/editor/singles/29.ts, src/db/src/actors/Discography/raw/editor/singles/30.ts, src/db/src/actors/Discography/raw/editor/singles/31.ts, src/db/src/actors/Songs/raw/editor/singles/31.ts
- Update 31st single formation
- Add trainees data
=> Update 31st Single Formation

src/db/result/album.json, src/db/result/search.json, src/db/result/song.json, src/db/src/actors/Discography/raw/editor/singles/31.ts, src/db/src/actors/Songs/constants/songTitle.ts, src/db/src/actors/Songs/raw/editor/singles/31.ts
=> Add 31st single songs

src/db/result/song.json, src/db/src/actors/Songs/raw/editor/singles/31.ts
=> Add 31st single mv director

src/db/result/member.json, src/db/result/members.json, src/db/src/actors/Members/raw/editor/firstGen.ts
- Update Saito Asuka graduation
=> Update asuka graduation
